#!/usr/bin/env bash
sudo userdel yashwant
sudo userdel hawk_tuah
sudo userdel looksmaxxer
sudo userdel skndash
sudo userdel brainrot_timmy
sudo userdel sigma_grinder
sudo rm -rf /home/yashwant /home/guards /home/bashers
sudo groupdel wardens
sudo groupdel guards
sudo groupdel bashers
echo "Cleanup done!"
